### ISSUE TITLE
Reproducability issue: tied_presults and presults are not defined

### ISSUE THREAD

**Issue by TaXxER** [amzn/debiased-balanced-interleaving#1]
I tried running the ipynb notebook to reproduce the results and figures from the paper.

However, I run into an issue in the cell that makes the first figure, i.e., the cell just below header `1. First fig in simulation section: correction reliability and power`.

In this cell, variables `tied_presults` and `presults` are among the arguments that are passed on to the `basic_plot`-method. These variables are not defined in the notebook. 

Could you guide me on how I should initialise these variables in order to be able to reproduce the your plots?

@castells @nanbi-amazon

**Comment by TaXxER** [comment]
After looking into it a little bit more, I believe that the solution is to add the following line to the cell below the `1. First fig in simulation section: correction reliability and power`:

```
tied_presults, presults = power_all(alpha, npoints, nreps, nsessions, nqueries, nonrel, rel, ranking_generator, customers, interleavers)
```

Can you confirm that this is indeed the correct fix?

**Comment by castells** [comment]
Thanks @TaXxER for spotting this! Indeed you got it right, that line needs to be uncommented. We had left a few lines commented out from our last iterations while running the experiments. I've just committed a full pass at the notebook hopefully fixing any such trailing bits and cleaning up a few unneeded comments and code, and I'm now doing a full run to test all is ok.
